version: '3.8'
services:
  mysql:
    image: mysql:8.0
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./database:/app
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: "mysql -h localhost -uroot -p${MYSQL_ROOT_PASSWORD} -e 'SELECT 1;'"
      interval: 10s
      timeout: 10s
      retries: 3
    command: --default-authentication-plugin=mysql_native_password

  server:
    container_name: 'server_bradery'
    build: ./server/
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - /var/express/node_modules/
      - ./server/:/app
    env_file:
      - .env

  web:
    container_name: 'web_bradery'
    build: ./web/
    ports:
      - "8081:8081"
    depends_on:
      - server
    volumes:
      - /var/react/node_modules/
      - ./web:/app

volumes:
  mysql-volume: